### ISSUE TITLE
ts: clean up ~953 pre-existing type errors and pin vue-tsc/typescript

### ISSUE THREAD

**Issue by laurigates** [ForumViriumHelsinki/R4C-Cesium-Viewer#721]
## What

After PR #720 lands `\"ignoreDeprecations\": \"6.0\"` to clear TS5101 (`baseUrl` deprecation halt), `bunx vue-tsc --noEmit` surfaces approximately 953 pre-existing type errors across ~113 files. These existed on `main` for some time but were masked because vue-tsc exited early at the deprecation message.

Sample failures from PR #720 CI: https://github.com/ForumViriumHelsinki/R4C-Cesium-Viewer/actions/runs/25483908103/job/74774527491

\`\`\`
src/App.vue(166,47): TS2551: Property 'postalCode' does not exist on type 'Store<...>'. Did you mean 'postalcode'?
src/components/AreaProperties.vue(326,15): TS2339: Property '_properties' does not exist on type 'never'.
src/components/BackgroundMapBrowser.vue(541,25): TS18047: 'globalStore.cesiumViewer' is possibly 'null'.
src/components/BuildingHeatChart.vue(33,14): TS2345: Argument of type 'null' is not assignable to parameter of type 'number'.
\`\`\`

## Why

Three orthogonal issues bundled here:

1. **\`vue-tsc\` / \`typescript\` are not pinned in \`devDependencies\`** — both are pulled transitively via \`bunx\`, so CI's behaviour drifts whenever a new TS or vue-tsc version ships. This made TS5101 appear suddenly when nothing in this repo changed.
2. **~953 type errors** across ~113 files, falling into roughly four buckets:
   - `Pinia store typing` — properties don't exist on `Store<...>` (case mismatches, missing fields)
   - `cesium runtime typing` — Cesium objects narrowed to `never` because of `as any` upstream
   - `null/undefined narrowing` — `globalStore.cesiumViewer` and similar are `T | null` and unguarded
   - `Element.style` access on generic `Element` type
3. **`baseUrl` deprecation** — TS 7.0 removes it. Migration is a `paths`-only refactor (mechanical).

## How

Suggested ordering (separate PRs):

1. **Pin `vue-tsc` and `typescript` in `devDependencies`** with explicit versions matching the current CI behaviour. One small PR. Stops drift.
2. **Bucket the 953 errors** by category and tackle each in its own PR:
   - Pinia stores → tighten store typings, fix property-name mismatches
   - Cesium typings → introduce typed wrappers or `import type` the relevant Cesium types
   - Null narrowing → add guards or non-null assertions where the runtime invariant is known
   - DOM `Element` casts → use `HTMLElement` / `SVGElement` where appropriate
3. **Migrate `baseUrl` → `paths`-only**. Remove `ignoreDeprecations` from `tsconfig.json` (the band-aid added in #720). Verify all `~/...` and bare-specifier imports still resolve.

## Out of scope

- Switching off `vue-tsc` for `tsc` (consider only if step 1 keeps drifting)
- Loosening strictness flags (`strict: false`, `noImplicitAny: false`) — would mask real bugs
- ESLint type-aware rules

## Acceptance

- `bunx vue-tsc --noEmit` exits 0 on `main`
- `vue-tsc` and `typescript` pinned with explicit versions
- `tsconfig.json` no longer needs `ignoreDeprecations`

## Related

- #720 — adds the `ignoreDeprecations: \"6.0\"` band-aid that surfaces this work
- #718 — separate test failures
- #719 — separate dependency vulnerabilities

**Comment by laurigates** [comment]
Interim CI unblock in #790: `continue-on-error: true` on the `vue-tsc` Typecheck step so the suite stops gating on the baseline while this cleanup is worked.

W22 typecheck status (2026-05-25, on `main` HEAD `4e7cd35`): **826 errors across ~110 files**. The categories track the original report — Pinia store-state inference failures (`null` defaults locking types), missing `vite/client` types for `import.meta.env`, ES2022 features (`Object.hasOwn`) used while tsconfig pins `lib: ["ES2020", ...]`, missing `import type Cesium from 'cesium'`, missing `window` augmentations for `__r4cPreloadErrorHandler*`, and `@template` generics in plain `.js` (`batchProcessor.js`).

Output still runs and is visible in the job log, so this issue's baseline can be driven by the same `vue-tsc --noEmit` run that CI emits.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by laurigates** [comment]
## Automated fix attempt — blocked by environment, no PR opened

An automated pass drafted all four changes this issue asks for, then **reverted them** because verification surfaced an environment blocker that would have produced a broken PR.

**Drafted changes (verified locally where possible):**
1. `package.json` — add `"vue-tsc": "^6.0.3"` + `"typescript": "^5.9.3"` to devDependencies and a `"typecheck": "vue-tsc --noEmit"` script
2. `.github/workflows/test.yml` — switch the typecheck step from `bunx vue-tsc --noEmit` to `bun run typecheck` (keeping `continue-on-error: true`)
3. `src/vite-env.d.ts` — new file with `/// <reference types="vite/client" />`
4. `tsconfig.json` — add `src/**/*.d.ts` to the include globs

**Blocker:** the sandbox's npm registry is a stale snapshot — `bun pm view vue-tsc dist-tags` reports `latest=3.3.2` (real npm is 6.x), and `bun install` fails with `No version matching "^6.0.3" found for specifier "vue-tsc"` even with `--registry https://registry.npmjs.org`. So `bun.lock` could not be regenerated. Shipping a `package.json` pinning `^6.0.3` **without** a matching resolvable `bun.lock` would break `bun install --frozen-lockfile` in every CI job — strictly worse than the current state.

**Secondary risk to verify:** with typescript 5.9.3, `tsc -p tsconfig.json` emits `error TS5103: Invalid value for '--ignoreDeprecations'` for the existing `ignoreDeprecations: "6.0"` band-aid (#720). That band-aid is only valid under the typescript 6.x bundled by vue-tsc 6.x, so the pinned pair needs a real vue-tsc-6 install to confirm peer-dep compatibility.

**Recommendation:** run this WO in an environment with live `npmjs.org` access so `bun install` can pin both deps and regenerate `bun.lock`, then verify `bun run typecheck` runs and the `ImportMeta.env` error count drops by 33.
