### ISSUE TITLE
Align ConstantProperty stubs in cesium-mock.ts and cesium-fixture.ts with setup.js convention

### ISSUE THREAD

**Issue by laurigates** [ForumViriumHelsinki/R4C-Cesium-Viewer#869]
## What

Two Cesium test doubles stub `ConstantProperty` as an **empty class with no `getValue()`**:

- `tests/mocks/cesium-mock.ts:419` — `ConstantProperty: class {}`
- `tests/fixtures/cesium-fixture.ts:486` — `ConstantProperty: class {}`

## Why

This is latent drift of the same shape that broke the **Integration Tests** check (fixed on `main` in 731ff0a / #856). Production reads entity properties via the public `ConstantProperty.getValue()` (see `.claude/rules/architecture.md` "Reading Cesium Entity Properties" and `.claude/rules/testing.md` "Mocking Cesium Entity Properties"). The empty-class stubs construct fine but throw `entity.properties?.x?.getValue is not a function` the moment any test exercising these doubles touches a code path that calls `.getValue()` on a `ConstantProperty`.

The comprehensive global mock in `tests/setup.js` and the per-file mock in `tests/integration/viewportBuildingLoader.test.js` already use the correct convention:

```js
ConstantProperty: vi.fn(function (value) {
	this._value = value
	this.getValue = vi.fn(() => value)
}),
```

## How

Replace both empty-class stubs with the `setup.js` convention (constructor storing the value behind a `getValue()`). No production change — these are test-only doubles.

## Acceptance

- `tests/mocks/cesium-mock.ts` and `tests/fixtures/cesium-fixture.ts` expose a `ConstantProperty` whose instances have a working `getValue()`.
- Existing test tiers stay green (`bun run test:integration`, accessibility/E2E unaffected).

## Context

Surfaced while fixing the recurring red Integration Tests check. The primary fix (the per-file mock) already landed via #856; closed redundant PR #868 noted this as the remaining follow-up.
