### PR TITLE
fix(types): drive vue-tsc to zero and pin vue-tsc/typescript

### LINKED ISSUE #721: ts: clean up ~953 pre-existing type errors and pin vue-tsc/typescript
## What

After PR #720 lands `\"ignoreDeprecations\": \"6.0\"` to clear TS5101 (`baseUrl` deprecation halt), `bunx vue-tsc --noEmit` surfaces approximately 953 pre-existing type errors across ~113 files. These existed on `main` for some time but were masked because vue-tsc exited early at the deprecation message.

Sample failures from PR #720 CI: https://github.com/ForumViriumHelsinki/R4C-Cesium-Viewer/actions/runs/25483908103/job/74774527491

\`\`\`
src/App.vue(166,47): TS2551: Property 'postalCode' does not exist on type 'Store<...>'. Did you mean 'postalcode'?
src/components/AreaProperties.vue(326,15): TS2339: Property '_properties' does not exist on type 'never'.
src/components/BackgroundMapBrowser.vue(541,25): TS18047: 'globalStore.cesiumViewer' is possibly 'null'.
src/components/BuildingHeatChart.vue(33,14): TS2345: Argument of type 'null' is not assignable to parameter of type 'number'.
\`\`\`

## Why

Three orthogonal issues bundled here:

1. **\`vue-tsc\` / \`typescript\` are not pinned in \`devDependencies\`** — both are pulled transitively via \`bunx\`, so CI's behaviour drifts whenever a new TS or vue-tsc version ships. This made TS5101 appear suddenly when nothing in this repo changed.
2. **~953 type errors** across ~113 files, falling into roughly four buckets:
   - `Pinia store typing` — properties don't exist on `Store<...>` (case mismatches, missing fields)
   - `cesium runtime typing` — Cesium objects narrowed to `never` because of `as any` upstream
   - `null/undefined narrowing` — `globalStore.cesiumViewer` and similar are `T | null` and unguarded
   - `Element.style` access on generic `Element` type
3. **`baseUrl` deprecation** — TS 7.0 removes it. Migration is a `paths`-only refactor (mechanical).

## How

Suggested ordering (separate PRs):

1. **Pin `vue-tsc` and `typescript` in `devDependencies`** with explicit versions matching the current CI behaviour. One small PR. Stops drift.
2. **Bucket the 953 errors** by category and tackle each in its own PR:
   - Pinia stores → tighten store typings, fix property-name mismatches
   - Cesium typings → introduce typed wrappers or `import type` the relevant Cesium types
   - Null narrowing → add guards or non-null assertions where the runtime invariant is known
   - DOM `Element` casts → use `HTMLElement` / `SVGElement` where appropriate
3. **Migrate `baseUrl` → `paths`-only**. Remove `ignoreDeprecations` from `tsconfig.json` (the band-aid added in #720). Verify all `~/...` and bare-specifier imports still resolve.

## Out of scope

- Switching off `vue-tsc` for `tsc` (consider only if step 1 keeps drifting)
- Loosening strictness flags (`strict: false`, `noImplicitAny: false`) — would mask real bugs
- ESLint type-aware rules

## Acceptance

- `bunx vue-tsc --noEmit` exits 0 on `main`
- `vue-tsc` and `typescript` pinned with explicit versions
- `tsconfig.json` no longer needs `ignoreDeprecations`

## Related

- #720 — adds the `ignoreDeprecations: \"6.0\"` band-aid that surfaces this work
- #718 — separate test failures
- #719 — separate dependency vulnerabilities

### PR DESCRIPTION
**Pull request by laurigates**
## What

Resolves the ~840 pre-existing `vue-tsc` type errors and pins the toolchain, so `vue-tsc --noEmit` exits **0** and the CI typecheck gate becomes blocking.

Fixes #721

## How it was diagnosed

The "~953" estimate came from CI's `bunx vue-tsc` silently pulling `typescript@latest` (6.0.3). Pinning `typescript@5.9.3` confirmed the **842 errors are genuine under 5.x too** — not a 6.x artifact. On 5.9.3 `baseUrl` is not a halting deprecation, so the `ignoreDeprecations: "6.0"` band-aid from #720 is removed and no `paths`-only migration is forced yet.

## Approach (5 commits)

1. **`build(deps)`** — pin `vue-tsc@3.3.3` + `typescript@5.9.3`, add a `typecheck` script. Stops the `bunx` drift that made TS5101 appear out of nowhere.
2. **`refactor(types)` foundation** — `src/types/cesium-global.d.ts` ambient shim (clears all 59 `Cesium` namespace errors) + typed Pinia store state (842 → 704).
3. **`refactor(types)` per-file** — guards (`?.`/`??`/early return), precise DOM casts, typed `ref` initializers, public Cesium APIs. 704 → 0.
4. **`test`** — adapt 4 unit-test files coupled to *private* Cesium internals to the public API the code now uses.
5. **`ci`** — make the typecheck job blocking via `bun run typecheck`.

## Verification

- ✅ `bun run typecheck` → **0 errors**
- ✅ `bun run lint` (biome) → clean
- ✅ `bun run test:unit` → **811 passed**, 4 skipped, 0 failed
- ✅ **No** `@ts-ignore` / `@ts-nocheck` / `@ts-expect-error` anywhere
- 12 narrow `/** @type {any} */` casts remain, each commented (window debug globals, runtime-assigned handles, Cesium `.d.ts` friction)

## Genuine runtime bugs fixed (surfaced by typing)

These are behavior changes — worth focused review:

- **mitt `eventBus.on()` returns `void`**, not an unsubscribe fn — several components stored & "called" it, leaking listeners on unmount (Scatterplot, SurveyScatterPlot, GridView, NearbyTreeArea).
- **Wrong store reads**: `helsinki.js`/`urbanheat.js` read `OtherNature`/`helsinkiView` off the wrong store → those layers never toggled.
- **Stale-arg calls**: `removeLandcover()`/`loadVegetation()`/`loadOtherNature()` passed args reading nonexistent `globalStore` props.
- **d3 `addTitle(..., margin)`** passed the whole margin object instead of `margin.top` → `NaN` title offsets (several charts).
- **`PostalCodeView`** read `store.urlStore.vegetation` (always `undefined`); restored the missing `urlStore.vegetation` getter.
- **`backgroundPreloader`** called nonexistent `progressiveLoader.loadChunked()`.
- **`CapitalRegion`** imported `@vueuse/core` (not a dependency) → replaced with a local debounce.
- **`entityPicker`** mutated the entity collection while iterating it.
- Stale `await provider.readyPromise` against Cesium 1.141 (removed API).

## Behavior-preserving migrations (why tests changed)

Production moved from private Cesium internals to public APIs — equivalent at runtime (real Cesium auto-coerces raw assignments and exposes `.values`):
- `entity._properties._value` → `entity.properties.getValue()`
- `viewer.entities._entities._array` → `viewer.entities.values`
- raw `polygon.outline = true` → `new Cesium.ConstantProperty(true)`

The 4 updated test files were asserting those private internals; they now assert the same values through the public API.

## Review guidance

This is large (119 files) but mechanical per-file. Highest-value review targets are the **genuine bug fixes** above. The `tsconfig` `lib` bump (ES2020 → ES2022) is to type `Object.hasOwn` (Biome's preferred form).

## Review feedback addressed (gemini-code-assist)

Follow-up commits responding to the inline review:

- **fix(charts):** `HeatHistogramHelsinki` still passed the whole `margin` object to `addTitle`/`addTitleWithLink` (the one chart missed by the `margin.top` sweep above), rendering a `NaN` title offset via `0 - top`. Both call sites now pass `margin.top`. Also made `SocioEconomicsChart`'s `heatData` consistently numeric (`Number()` on both ternary branches).
- **refactor(types):** finished the private→public Cesium read migration in the files this batch touched — `buildingFilter`, `tree`, `othernature`, `sensor`, `vegetation` now read via `ConstantProperty.getValue()` instead of `._value`, and the now-orphaned `TreeEntity` cast/typedef was removed. `sensor.test` mocks updated to the public surface. `vue-tsc` stays at 0; 811 unit tests pass.

## Follow-up

A pre-existing latent bug was found but **not** fixed (out of scope — needs a data-flow change, not a type fix): `CoolingCenterOptimiser` reads `bestCell.entity`, which `mitigationStore.setGridCells` intentionally never populates. Tracked separately.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by laurigates** [comment]
Follow-up for the pre-existing `CoolingCenterOptimiser` bug noted above: #839

File: src/components/HeatHistogramHelsinki.vue [hunk 1]
```diff
@@ -126,7 +129,11 @@ export default {
 					svg,
 					`Heat exposure to buildings in ${store.nameOfZone}`,
 					width,
-					margin
+					// plot.js's `addTitle` JSDoc declares `top: number`, but every caller
+					// (BuildingTreeChart, VulnerabilityChart, etc.) passes the `margin`
+					// object as the 4th arg. plot.js is out of this batch's scope, so the
+					// runtime value is preserved and cast to satisfy the inaccurate signature.
+					/** @type {number} */ (/** @type {unknown} */ (margin))
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/components/HeatHistogramHelsinki.vue]: Fixed in dc01c46. You're right — this was the one chart the PR's `margin.top` sweep missed. `addTitle` does `.attr('y', 0 - top)`, and `margin` is `{top,right,bottom,left}`, so `0 - margin` → `NaN`. Both this call **and** the adjacent `addTitleWithLink` (which had the identical latent bug) now pass `margin.top`, matching the sibling charts. The "preserve runtime value" comment was removed — its premise (that every caller passes the `margin` object) was incorrect.

File: src/components/SocioEconomicsChart.vue [hunk 2]
```diff
@@ -172,7 +184,7 @@ export default {
 				const selectedNimi = propsStore.socioEconomics
 				const compareData = socioEconomicsStore.getDataByNimi(selectedNimi)
 				const heatData = toggleStore.capitalRegionCold
-					? 1 - globalStore.averageHeatExposure.toFixed(3) // Use cold exposure data if cold toggle is active
+					? 1 - Number(globalStore.averageHeatExposure.toFixed(3)) // Use cold exposure data if cold toggle is active
 					: globalStore.averageHeatExposure.toFixed(3) // Use heat exposure data
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/components/SocioEconomicsChart.vue]: Fixed in dc01c46 — wrapped the heat branch in `Number(...)` so `heatData` is a `number` on both ternary branches, matching what `calculateYValues` expects.

File: src/services/building/buildingFilter.js [hunk 3]
```diff
@@ -84,7 +84,7 @@ export class BuildingFilter {
 
 				// Check hideNewBuildings filter
 				if (hideNewBuildings) {
-					const completionDate = entity._properties?._c_valmpvm?._value
+					const completionDate = entity.properties?._c_valmpvm?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/building/buildingFilter.js]: Accepted in 0bf0224 — migrated to `.getValue()`.

File: src/services/building/buildingFilter.js [hunk 4]
```diff
@@ -93,10 +93,10 @@ export class BuildingFilter {
 				// Check hideNonSote filter (social/healthcare buildings)
 				if (!shouldHide && hideNonSote) {
 					const kayttotark = helsinkiView
-						? entity._properties?._c_kayttark?._value
-							? Number(entity._properties?._c_kayttark?._value)
+						? entity.properties?._c_kayttark?._value
+							? Number(entity.properties?._c_kayttark?._value)
 							: null
-						: entity._properties?._kayttarks?._value
+						: entity.properties?._kayttarks?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/building/buildingFilter.js]: Accepted in 0bf0224 — migrated to `.getValue()`.

File: src/services/building/buildingFilter.js [hunk 5]
```diff
@@ -110,7 +110,7 @@ export class BuildingFilter {
 				// Check hideLow filter (buildings with <= 6 floors)
 				if (!shouldHide && hideLow) {
 					const floorCount =
-						entity._properties?.[helsinkiView ? '_i_kerrlkm' : '_kerrosten_lkm']?._value
+						entity.properties?.[helsinkiView ? '_i_kerrlkm' : '_kerrosten_lkm']?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/building/buildingFilter.js]: Accepted in 0bf0224 — migrated to `.getValue()`.

File: src/services/building/buildingFilter.js [hunk 6]
```diff
@@ -175,7 +177,7 @@ export class BuildingFilter {
 			? visibleEntities.map((entity) => entity.properties?._avgheatexposuretobuilding?._value)
 			: visibleEntities
 					.map((entity) => {
-						const heatTimeseries = entity.properties.heat_timeseries?._value || []
+						const heatTimeseries = entity.properties?.heat_timeseries?._value || []
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/building/buildingFilter.js]: Accepted in 0bf0224 — migrated to `.getValue()`.

File: src/services/tree.js [hunk 7]
```diff
@@ -224,14 +247,17 @@ export default class Tree {
...
-			kohde_id: entity._properties?._kohde_id?._value,
-			p_ala_m2: entity._properties?._p_ala_m2?._value,
-		}))
+		const treeData = entities.map((entity) => {
+			const e = /** @type {TreeEntity} */ (entity)
+			return {
+				kohde_id: e._properties?._kohde_id?._value,
+				p_ala_m2: e._properties?._p_ala_m2?._value,
+			}
+		})
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/tree.js]: Accepted in 0bf0224 — reads `entity.properties?.kohde_id/p_ala_m2?.getValue()` and the `TreeEntity` cast is gone. The now-orphaned `TreeEntity` typedef was removed too.

File: src/services/tree.js [hunk 8]
```diff
@@ -224,14 +247,17 @@ export default class Tree {
...
 
 		// Extract serializable building data (prevents DataCloneError)
 		const buildingData = new Map()
-		const buildingEntities = buildingsDataSource.entities.values
+		const buildingEntities = /** @type {TreeEntity[]} */ (buildingsDataSource.entities.values)
 		for (const entity of buildingEntities) {
 			const id = entity._properties?._id?._value || entity._properties?._hki_id?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/tree.js]: Accepted in 0bf0224 — the whole building-data extraction loop now uses public `properties` + `.getValue()` (`id`/`hki_id`/`avgheatexposuretobuilding`/`area_m2`), so the `TreeEntity[]` cast was dropped.

File: src/services/tree.js [hunk 9]
```diff
@@ -322,12 +348,15 @@ export default class Tree {
...
+			const polygon = /** @type {any} */ (entity.polygon)
+			if (polygon) {
+				polygon.outlineColor = Cesium.Color.BLACK
+				polygon.outlineWidth = 3
+			}
 
-			if (entity._properties._description && entity.polygon) {
+			if (entity._properties?._description && polygon) {
 				this.setTreePolygonMaterialColor(entity, entity._properties._description._value)
 			}
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/tree.js]: Accepted in 0bf0224 — `resetTreeEntities` now reads `entity.properties?.description?.getValue()` and the `TreeEntity` cast is gone (typedef removed). `setTreePolygonMaterialColor` still reads `_properties._korkeus_ka_m` via its `Object`-typed param — out of this thread's scope, left as a follow-up.

File: src/services/othernature.js [hunk 10]
```diff
@@ -82,7 +87,7 @@ export default class Othernature {
 
 				// Process batch
 				for (const entity of batch) {
-					const category = entity.properties._koodi?._value
+					const category = entity.properties?._koodi?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/othernature.js]: Accepted in 0bf0224 — migrated to `.getValue()`.

File: src/services/sensor.js [hunk 11]
```diff
@@ -75,7 +75,7 @@ export default class Vegetation {
 		// Iterate over the entities and add labels for "temp_air" and "rh_air"
 		for (let i = 0; i < entities.length; i++) {
 			const entity = entities[i]
-			const measurement = entity.properties._measurement._value
+			const measurement = entity.properties?._measurement?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/sensor.js]: Accepted in 0bf0224 — migrated to `.getValue()`. The `sensor.test` mock was updated from `{ _value }` to `{ getValue: () => … }` to match the public surface (the unit suite caught it; mirrors 91a2721).

File: src/services/vegetation.js [hunk 12]
```diff
@@ -82,7 +93,7 @@ export default class Vegetation {
 
 				// Process batch
 				for (const entity of batch) {
-					const category = entity.properties._koodi?._value
+					const category = entity.properties?._koodi?._value
```
[the remark this answers is not in the document]
Comment (laurigates) [reply src/services/vegetation.js]: Accepted in 0bf0224 — migrated to `.getValue()`.
